# version: '3.8'

# services:
#   nestjs_api_prod:
#     build:
#       context: .
#       dockerfile: Dockerfile.prod
#     ports:
#       - '3001:3001'
#     environment:
#       - PORT=3001
#       - NODE_ENV=production
#     volumes:
#       - ./src:/usr/src/app/src

version: '3.8'

services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DATABASE_USERNAME= ${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - ./src:/usr/src/app/src