# version: '3.8'

# services:
#   nestjs_api_prod:
#     build:
#       context: .
#       dockerfile: Dockerfile.prod
#     ports:
#       - '3001:3001'
#     environment:
#       - PORT=3001
#       - NODE_ENV=production
#     volumes:
#       - ./src:/usr/src/app/src

version: '3.8'

services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DATABASE_USERNAME=muky_albany
      - DATABASE_PASSWORD=iOoWAcFOvQUPnqooXU9II2kvNLgd7KQ0
      - DATABASE_NAME=grambutler
    volumes:
      - ./src:/usr/src/app/src